// 中文语言包
export default {
  /**
   * 公共
   */
  common: {
    detail: '详情',
    description: '描述',
    close: '关闭',
    configuration: '配置',
    day: '天',
    hour: '小时',
    minute: '分钟',
    currentLocation: '当前位置: ',
    member: '会员',
    admin: '管理员',
    superAdmin: '超级管理员',
    ordinaryUsers: '普通用户',
    managementSystem: '软星管理系统',
    username: '账号',
    password: '密码',
    zh: '中文',
    en: '英文',
    pleaseCheckInput: '请检查您的输入!',
    pleaseInput: '请输入',
    unfold: '展开',
    shrink: '收缩',
    fail: '失败',
    all: '全部',
    state: '状态',
    createTime: '创建时间',
    updateTime: '更新时间',
    option: '操作',
    reset: '重置',
    search: '搜索',
    confirm: '确认',
    cancel: '取消',
    normal: '启用',
    disable: '禁用',
    add: '添加',
    edit: '编辑',
    deleteSelected: '批量删除',
    exportToData: '导出数据',
    refresh: '刷新',
    id: '编号',
    delete: '删除',
    theColumnsThatAreDisplayed: '显示的列',
    upload: '点击上传',
    selectImage: '选择图片',
    uploading: '上传中',
    field: '字段',
    filename: '文件名',
    customize: '自定义',
    language: '语言',
    pages: '页',
    languageSwitching: '语言切换',
    theCurrentlySelectedRow: '当前选中的行',
    theFileNameIsNotEmpty: '文件名不为空!',
    contentHeightDisplayAdjustment: '内容高度显示调整', //
    theFileNameConsistsOfEnglishDigitsChineseCharactersAndUnderscores:
      '文件名由英文数字、中文字符和下划线组成',
    theFieldContainsAtLeastOne: '字符至少包含一个!',
  },

  /**
   * 顶部导航栏
   */
  header: {
    theme: '主题',
    fullScreen: '全屏',
    themeSwitching: '主题切换',
    enterFullScreenMode: '进入全屏',
    logout: '退出',
    languageSwitching: '语言切换',
    language: '语言',
    exited: '已退出',
  },

  /**
   * 日志
   */
  role: {
    roleValueMin: '权限值最小为1!',
    roleValueNoEmpty: '权限值不为空!',
    roleNameNoEmpty: '角色名称不为空!',
    roleValue: '权限值',
    roleName: '角色名称',
    permission: '权限',
  },

  /**
   * 用户信息
   */
  user: {
    role: '角色',
    username: '账号',
    pleaseInputUsername: '请输入您的用户名!',
    sex: '性别',
    nickname: '名称',
    girl: '女',
    boy: '男',
    phone: '手机号',
    avatar: '头像',
    roleNoEmpty: '角色不为空!',
    usernameNoEmpty: '账号不为空!',
    nicknameNoEmpty: '名称不为空!',
    nicknameFormatError: '名称格式错误!',
    avatarNoEmpty: '头像不为空!',
    phoneNumberFormatError: '手机号格式错误!',
    phoneNumberNoEmpty: '手机号不为空!',
    passwordNoEmpty: '密码不为空!',
    containsOnlyEnglishAndNumbers: '只包含 英文、数字,长度最小为5!',
    Mustleast6CharactersLettersDigitsUnderscores:
      '至少6个字符、字母、数字、下划线!',
  },

  /**
   * 用户信息
   */
  admin: {
    role: '角色',
    username: '账号',
    pleaseInputUsername: '请输入您的用户名!',
    sex: '性别',
    nickname: '名称',
    girl: '女',
    boy: '男',
    phone: '手机号',
    avatar: '头像',
    roleNoEmpty: '角色不为空!',
    usernameNoEmpty: '账号不为空!',
    nicknameNoEmpty: '名称不为空!',
    nicknameFormatError: '名称格式错误!',
    avatarNoEmpty: '头像不为空!',
    phoneNumberFormatError: '手机号格式错误!',
    phoneNumberNoEmpty: '手机号不为空!',
    passwordNoEmpty: '密码不为空!',
    containsOnlyEnglishAndNumbers: '只包含 英文、数字,长度最小为5!',
    Mustleast6CharactersLettersDigitsUnderscores:
      '至少6个字符、字母、数字、下划线!',
  },

  /**
   * 通用配置
   */
  config: {
    key: '键名',
    value: '键值',
    description: '描述',
  },

  /**
   * 系统信息
   */
  sys: {
    startTime: '启动时间',
    runningTime: '运行时长',
    jvm: '虚拟机',
    logicCPU: '逻辑CPU',
    physicalCPU: '物理CPU',
    physicalCore: '物理核心',
    model: '型号',
    core: ' 核心',
    operatingSystem: '操作系统',
    runTime: '运行时长',
    ip: 'IP',
    cpu: 'CPU使用率',
    disk: '磁盘使用率',
    switchboard: '交换机使用率',
    memory: '内存使用率',
    physicalMemoryCapacity: '物理内存容量',
    diskStorageCapacity: '磁盘存储容量',
    exchangeSpaceCapacity: '交换空间容量',
    systemInformation: '系统信息',
    otherInformation: '其他信息',
  },

  /**
   * 菜单
   */
  menu: {
    task: '任务管理',
    general: '通用配置',
    role: '角色管理',
    oplog: '操作日志',
    monitor: '系统监控',
    404: '页面不存在',
    home: '首页',
    sysAdmin: '系统管理',
    administrator: '管理人员',
    userAdmin: '用户管理',
    user: '用户管理',
    admin: '管理人员',
    sys: '系统管理',
    onlyOpenCurrentMenu: '是否只展开当前菜单?',
  },

  /**
   * 任务管理页面
   */
  task: {
    testTask:"测试任务",
    taskStop: '任务停止',
    taskStart: '任务启动',
    cornExpression: 'CORN 表达式',
    fireNow: '立即执行一次',
    withNextFireTime: '不补偿任何误点',
    ignoreMisfires: '补偿所有误点',
    frequency: '执行频率',
    cycle: '执行周期（次）',
    mistakeMode: '误点模式',
    hour: '小时',
    minutes: '分钟',
    seconds: '秒',
    pleaseSelectATime: '请选择时间',
    normalMode: '普通模式',
    cornMode: 'CORN模式',
    corn: 'CORN表达式',
    triggerConfig: '触发配置',
    jobCodeNoEmpty: '任务编码不为空',
    duration: '起止时间',
    jobName: '任务名称',
    username: '发布人',
    expression: '表达式',
    groupName: '分组名称',
    jobCode: '任务编码',
    startTime: '开始时间',
    endTime: '结束时间',
    unit: '单位',
    model: '模式',
  },

  /**
   * 日志
   */
  oplog: {
    type: '类型',
    code: '状态码',
    data: '数据',
    msg: '消息',
    package: '包名',
    method: '方法名',
    message: '提示信息',
    localizedMessage: '错误信息',
    errorInfo: '错误信息',
    query: '操作参数',
    times: '耗时',
    nickname: '操作用户',
    sys: '系统模块',
    error: '失败',
    success: '成功',
    address: '归属地址',
    critical: '核心',
    important: '重要',
    general: '一般',
    secure: '安全模块',
    user: '用户模块',
    category: '操作类型',
    description: '操作信息',
    model: '系统模块',
    ip: 'IP地址',
    result: '操作结果',
    oplog: '操作日志',
  },

  /**
   * 登录页面
   */
  p_login: {
    login: '登录',
    verifyCode: '验证码',
    slogan: '以客户为中心，以效率为动力!',
    administration: '管理系统',
    themeSwitching: '主题切换',
    languageSwitching: '语言切换',
    pleaseInputPassword: '请输入您的密码!',
    pleaseInputVerifyCode: '请输入您的验证码!',
    acquisitionFailed: '获取验证码失败',
    obtainVerificationCode: '点击获取验证码',
    success: '登录成功',
    loggingIn: '登录中...',
  },

  /**
   * 消息
   */
  message: {
    exportingIrogress: '导出中...',
    exportComplete: '导出完成', //
    unauthorizedOperation: '无权操作！',
    uploadSuccess: '上传成功',
    addSuccess: '添加成功',
    editSuccess: '编辑成功',
    committing: '提交中...',
    youSureProceedThisOperation: '您确定要执行此操作?',
    pleaseCheck: '请检查!',
    quantity: '数量',
    deleteSuccess: '删除成功',
    errorDelete: '删除失败！',
    error: '错误',
    invalidAccounts: '无效账户！',
    accountRepeat: '账号已存在！',
    errorEnroll: '注册失败！',
    errorAdd: '添加失败！',
    uploadMaxSize: '上传图片限制5M以内!',
    uploadType: '上传图片类型错误！',
    errorUpdate: '更新失败!',
    errorLogin: '请先登录!',
    errorAuthorized: '授权失败!',
    errorUser: '用户不存在!',
    authenticationFailed: '认证失败!',
    errorCache: '验证码错误!',
    systemBusy: '系统繁忙!',
    success: '成功',
    ok: '成功',
    no: '失败',
    fail: '失败',
    NetworkAbnormal: '网络异常!',
    SemanticsWrong: '语义错误!',
    ServerAuthenticationFailed: '服务器身份验证失败!',
    ServerDeniesAccess: '服务器拒绝访问!',
    RequestAddressIncorrect: '请求地址不正确!',
    ServerNoResponding: '服务器无响应!',
    NetworkError: '网络错误!',
    codeNoEmpty: 'code 不为空!',
    numberQueriesNotEmpty: '查询个数不为空!',
    pageNumbersNoEmpty: '页码不为空!',
    illegalPageNumbers: '非法页码!',
    stateNoEmpty: '状态不为空!',
    valueNoEmpty: '值不为空!',
    sexNoEmpty: '性别不为空!',
    illegalState: '非法状态!',
    illegalId: '非法id!',
    illegalSex: '非法性别!',
    illegalRole: '非法角色!',
    idNotEmpty: 'id不为空!',
    captchaNotEmpty: '验证码不为空!',
    roleNoEmpty: '角色不为空!',
    usernameNoEmpty: '账号不为空!',
    nicknameNoEmpty: '名称不为空!',
    nicknameFormatError: '名称格式错误!',
    avatarNoEmpty: '头像不为空!',
    phoneNumberFormatError: '手机号格式错误!',
    phoneNumberNoEmpty: '手机号不为空!',
    passwordNoEmpty: '密码不为空!',
    phoneNumberHasBeenUsed: '手机号已被使用!',
    errorPassword: '密码错误!',
    preparingPleaseWait: '准备中,请稍后...',
    NetworkReconnection: '网络重连',
  },
}
