spring:
  #  数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/rxls_2.0?useSSL=false&allowPublicKeyRetrieval=true
    username: rxls_2.0
    password: D6ZGSNazC5ZxwTDf
    driver-class-name: com.mysql.cj.jdbc.Driver
